version: '3.1'

services:
  bird_flask:
    container_name: api
    build:
        context: ./app
    command: python main.py
    ports:
      - "5000:5000"
    env_file:
      - "app/.env"

networks:
  overlay:
